package com.analyzer;

/* The following code was generated by JFlex 1.7.0 */

import java_cup.runtime.*;
import java.io.*;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.7.0
 * from the specification file <tt>jflex_rules.flex</tt>
 */
class Lexer implements java_cup.runtime.Scanner, sym {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;
  public static final int STRING = 2;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  1,  2, 2
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\12\1\14\1\21\1\21\1\13\22\0\1\20\1\63\1\76"+
    "\1\22\1\0\1\57\1\60\1\77\1\71\1\71\1\16\1\56\1\67"+
    "\1\11\1\7\1\15\1\4\11\2\1\70\1\64\1\55\1\54\1\53"+
    "\1\75\1\0\4\6\1\10\1\6\21\1\1\5\2\1\1\72\1\17"+
    "\1\73\1\61\1\3\1\0\1\23\1\27\1\33\1\40\1\31\1\41"+
    "\1\45\1\35\1\37\1\1\1\32\1\42\1\43\1\36\1\26\1\51"+
    "\1\1\1\30\1\34\1\25\1\24\1\52\1\47\1\44\1\50\1\46"+
    "\1\65\1\62\1\66\1\74\6\0\1\21\u1fa2\0\1\21\1\21\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\udfe6\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\3\0\1\1\1\2\1\3\1\1\1\3\1\4\1\5"+
    "\2\6\1\7\1\10\1\11\1\1\17\2\1\12\1\13"+
    "\1\14\1\15\1\16\1\17\1\20\1\21\1\22\1\23"+
    "\1\24\1\25\1\26\1\27\1\30\1\31\1\32\1\33"+
    "\1\34\1\35\1\36\1\37\1\6\1\1\1\40\1\41"+
    "\2\1\1\0\1\42\1\43\1\44\1\45\1\0\1\46"+
    "\1\47\1\50\20\2\1\51\1\52\7\2\1\53\1\54"+
    "\1\55\1\56\1\57\1\60\1\61\1\62\1\63\1\64"+
    "\1\65\1\66\1\67\1\70\1\37\1\0\1\3\1\71"+
    "\2\45\1\0\23\2\1\72\2\2\1\73\6\2\1\74"+
    "\1\75\1\41\1\0\1\76\6\2\1\77\1\100\1\2"+
    "\1\101\2\2\1\102\11\2\1\103\1\104\1\2\1\105"+
    "\2\2\1\106\1\2\1\107\4\2\1\110\2\2\1\111"+
    "\5\2\1\112\1\113\3\2\1\114\1\2\1\115\1\2"+
    "\1\116\1\117\1\120\1\121\1\122\1\123\3\2\1\124"+
    "\2\2\1\125\1\2\1\126\1\127\1\130\1\131";

  private static int [] zzUnpackAction() {
    int [] result = new int[219];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\100\0\200\0\300\0\u0100\0\u0140\0\u0180\0\u01c0"+
    "\0\u0200\0\u0240\0\u0280\0\u02c0\0\300\0\u0300\0\u0340\0\u0380"+
    "\0\u03c0\0\u0400\0\u0440\0\u0480\0\u04c0\0\u0500\0\u0540\0\u0580"+
    "\0\u05c0\0\u0600\0\u0640\0\u0680\0\u06c0\0\u0700\0\u0740\0\u0780"+
    "\0\u07c0\0\u0800\0\u0840\0\u0880\0\u08c0\0\u0900\0\u0940\0\u0980"+
    "\0\300\0\300\0\300\0\300\0\u09c0\0\300\0\300\0\300"+
    "\0\300\0\300\0\300\0\u0a00\0\u0a40\0\300\0\u0a80\0\300"+
    "\0\u0ac0\0\u0b00\0\u0b40\0\u0b80\0\300\0\300\0\300\0\u0bc0"+
    "\0\u0c00\0\300\0\300\0\300\0\u0c40\0\u0c80\0\u0cc0\0\u0d00"+
    "\0\u0d40\0\u0d80\0\u0dc0\0\u0e00\0\u0e40\0\u0e80\0\u0ec0\0\u0f00"+
    "\0\u0f40\0\u0f80\0\u0fc0\0\u1000\0\u0100\0\u1040\0\u1080\0\u10c0"+
    "\0\u1100\0\u1140\0\u1180\0\u11c0\0\u1200\0\u1240\0\300\0\300"+
    "\0\300\0\u1280\0\300\0\300\0\300\0\300\0\300\0\300"+
    "\0\300\0\300\0\300\0\300\0\u12c0\0\u0b40\0\300\0\u1300"+
    "\0\300\0\u1340\0\u1380\0\u13c0\0\u1400\0\u1440\0\u1480\0\u14c0"+
    "\0\u1500\0\u1540\0\u1580\0\u15c0\0\u1600\0\u1640\0\u1680\0\u16c0"+
    "\0\u1700\0\u1740\0\u1780\0\u17c0\0\u1800\0\u0100\0\u1840\0\u1880"+
    "\0\u0100\0\u18c0\0\u1900\0\u1940\0\u1980\0\u19c0\0\u1a00\0\300"+
    "\0\300\0\u1a40\0\u1a40\0\u0100\0\u1a80\0\u1ac0\0\u1b00\0\u1b40"+
    "\0\u1b80\0\u1bc0\0\u0100\0\u0100\0\u1c00\0\u0100\0\u1c40\0\u1c80"+
    "\0\u0100\0\u1cc0\0\u1d00\0\u1d40\0\u1d80\0\u1dc0\0\u1e00\0\u1e40"+
    "\0\u1e80\0\u1ec0\0\u0100\0\u0100\0\u1f00\0\u0100\0\u1f40\0\u1f80"+
    "\0\u0100\0\u1fc0\0\u0100\0\u2000\0\u2040\0\u2080\0\u20c0\0\u0100"+
    "\0\u2100\0\u2140\0\u0100\0\u2180\0\u21c0\0\u2200\0\u2240\0\u2280"+
    "\0\u0100\0\u0100\0\u22c0\0\u2300\0\u2340\0\u0100\0\u2380\0\u0100"+
    "\0\u23c0\0\u0100\0\u0100\0\u0100\0\u0100\0\u0100\0\u0100\0\u2400"+
    "\0\u2440\0\u2480\0\u0100\0\u24c0\0\u2500\0\u0100\0\u2540\0\u0100"+
    "\0\u0100\0\u0100\0\u0100";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[219];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\4\1\5\1\6\1\7\1\10\2\5\1\11\1\5"+
    "\1\12\1\13\1\14\1\15\1\16\1\17\1\20\1\13"+
    "\1\0\1\4\1\21\1\22\1\23\1\5\1\24\1\25"+
    "\1\26\1\5\1\27\1\30\2\5\1\31\1\32\1\33"+
    "\1\34\2\5\1\35\1\5\1\36\2\5\1\37\1\40"+
    "\1\41\1\42\1\43\1\44\1\45\1\46\1\47\1\50"+
    "\1\51\1\52\1\53\1\54\1\55\1\56\1\57\1\60"+
    "\1\61\1\62\1\63\2\4\1\5\1\6\1\7\1\10"+
    "\2\5\1\11\1\5\1\12\1\13\1\14\1\15\1\16"+
    "\1\17\1\20\1\13\1\0\1\64\1\21\1\22\1\23"+
    "\1\5\1\24\1\25\1\26\1\5\1\27\1\30\2\5"+
    "\1\31\1\32\1\33\1\34\2\5\1\35\1\5\1\36"+
    "\2\5\1\37\1\40\1\41\1\42\1\43\1\44\1\45"+
    "\1\46\1\47\1\50\1\51\1\52\1\53\1\54\1\55"+
    "\1\56\1\57\1\60\1\61\1\62\1\63\1\4\7\65"+
    "\1\4\3\65\1\14\1\66\2\65\1\67\1\4\55\65"+
    "\1\70\1\65\101\0\6\5\1\0\1\5\12\0\30\5"+
    "\26\0\1\7\1\6\1\0\1\6\2\7\1\71\1\7"+
    "\12\0\30\7\26\0\6\7\1\0\1\7\12\0\30\7"+
    "\26\0\1\7\1\72\1\0\1\72\1\73\1\7\1\71"+
    "\1\7\12\0\21\7\1\73\6\7\34\0\1\74\101\0"+
    "\1\75\41\0\1\76\1\77\35\0\1\13\5\0\1\13"+
    "\73\0\1\66\100\0\1\100\1\101\35\0\1\102\77\0"+
    "\1\103\23\0\13\104\2\0\4\104\1\0\56\104\1\0"+
    "\6\5\1\0\1\5\12\0\1\5\1\105\26\5\26\0"+
    "\6\5\1\0\1\5\12\0\13\5\1\106\14\5\26\0"+
    "\6\5\1\0\1\5\12\0\25\5\1\107\2\5\26\0"+
    "\6\5\1\0\1\5\12\0\5\5\1\110\22\5\26\0"+
    "\6\5\1\0\1\5\12\0\6\5\1\111\21\5\26\0"+
    "\6\5\1\0\1\5\12\0\13\5\1\112\3\5\1\113"+
    "\1\5\1\114\6\5\26\0\6\5\1\0\1\5\12\0"+
    "\1\115\2\5\1\116\6\5\1\117\15\5\26\0\6\5"+
    "\1\0\1\5\12\0\2\5\1\120\7\5\1\121\1\5"+
    "\1\122\7\5\1\123\3\5\26\0\6\5\1\0\1\5"+
    "\12\0\13\5\1\124\2\5\1\125\11\5\26\0\6\5"+
    "\1\0\1\5\12\0\3\5\1\126\2\5\1\127\21\5"+
    "\26\0\6\5\1\0\1\5\12\0\3\5\1\130\13\5"+
    "\1\131\10\5\26\0\6\5\1\0\1\5\12\0\3\5"+
    "\1\132\24\5\26\0\6\5\1\0\1\5\12\0\3\5"+
    "\1\133\24\5\26\0\6\5\1\0\1\5\12\0\12\5"+
    "\1\134\15\5\26\0\6\5\1\0\1\5\12\0\3\5"+
    "\1\135\24\5\100\0\1\136\1\137\77\0\1\140\77\0"+
    "\1\141\1\142\1\0\1\52\10\0\1\57\63\0\1\143"+
    "\1\0\1\144\74\0\1\53\1\145\77\0\1\146\3\0"+
    "\1\147\73\0\1\150\77\0\1\151\5\0\1\152\71\0"+
    "\1\153\76\0\1\60\24\0\13\64\2\0\4\64\1\0"+
    "\56\64\7\65\1\0\3\65\2\0\2\65\2\0\55\65"+
    "\1\0\1\65\13\104\2\0\2\104\1\154\1\104\1\0"+
    "\3\104\1\154\1\104\2\154\5\104\1\154\2\104\1\154"+
    "\34\104\2\154\2\0\1\71\1\0\1\71\3\0\1\155"+
    "\20\0\1\155\47\0\1\7\1\72\1\0\1\72\2\7"+
    "\1\71\1\7\12\0\30\7\26\0\1\7\1\156\1\7"+
    "\1\156\1\7\1\156\1\0\1\156\12\0\1\156\3\7"+
    "\1\156\1\7\1\156\1\7\1\156\4\7\2\156\11\7"+
    "\34\0\1\157\70\0\13\100\1\160\1\161\63\100\16\101"+
    "\1\162\61\101\1\0\6\5\1\0\1\5\12\0\2\5"+
    "\1\163\25\5\26\0\6\5\1\0\1\5\12\0\11\5"+
    "\1\164\2\5\1\165\13\5\26\0\6\5\1\0\1\5"+
    "\12\0\26\5\1\166\1\5\26\0\6\5\1\0\1\5"+
    "\12\0\6\5\1\167\21\5\26\0\6\5\1\0\1\5"+
    "\12\0\2\5\1\170\17\5\1\171\5\5\26\0\6\5"+
    "\1\0\1\5\12\0\1\5\1\172\26\5\26\0\6\5"+
    "\1\0\1\5\12\0\11\5\1\173\16\5\26\0\6\5"+
    "\1\0\1\5\12\0\2\5\1\174\25\5\26\0\6\5"+
    "\1\0\1\5\12\0\11\5\1\175\16\5\26\0\6\5"+
    "\1\0\1\5\12\0\13\5\1\176\14\5\26\0\6\5"+
    "\1\0\1\5\12\0\1\177\27\5\26\0\6\5\1\0"+
    "\1\5\12\0\1\200\4\5\1\201\22\5\26\0\6\5"+
    "\1\0\1\5\12\0\3\5\1\202\24\5\26\0\6\5"+
    "\1\0\1\5\12\0\22\5\1\203\1\204\4\5\26\0"+
    "\6\5\1\0\1\5\12\0\14\5\1\205\13\5\26\0"+
    "\6\5\1\0\1\5\12\0\2\5\1\206\25\5\26\0"+
    "\6\5\1\0\1\5\12\0\1\5\1\207\26\5\26\0"+
    "\6\5\1\0\1\5\12\0\16\5\1\210\11\5\26\0"+
    "\6\5\1\0\1\5\12\0\5\5\1\211\22\5\26\0"+
    "\6\5\1\0\1\5\12\0\3\5\1\212\24\5\26\0"+
    "\6\5\1\0\1\5\12\0\13\5\1\213\14\5\26\0"+
    "\6\5\1\0\1\5\12\0\2\5\1\214\25\5\26\0"+
    "\6\5\1\0\1\5\12\0\14\5\1\215\13\5\26\0"+
    "\6\5\1\0\1\5\12\0\14\5\1\216\2\5\1\217"+
    "\10\5\101\0\1\220\77\0\1\221\25\0\1\222\1\0"+
    "\1\222\4\0\1\223\44\0\1\223\35\0\1\161\63\0"+
    "\15\101\1\161\1\162\61\101\1\0\6\5\1\0\1\5"+
    "\12\0\3\5\1\224\24\5\26\0\6\5\1\0\1\5"+
    "\12\0\14\5\1\225\13\5\26\0\6\5\1\0\1\5"+
    "\12\0\3\5\1\226\24\5\26\0\6\5\1\0\1\5"+
    "\12\0\6\5\1\227\21\5\26\0\6\5\1\0\1\5"+
    "\12\0\1\230\27\5\26\0\6\5\1\0\1\5\12\0"+
    "\1\5\1\231\26\5\26\0\6\5\1\0\1\5\12\0"+
    "\14\5\1\232\13\5\26\0\6\5\1\0\1\5\12\0"+
    "\20\5\1\233\7\5\26\0\6\5\1\0\1\5\12\0"+
    "\6\5\1\234\21\5\26\0\6\5\1\0\1\5\12\0"+
    "\6\5\1\235\21\5\26\0\6\5\1\0\1\5\12\0"+
    "\6\5\1\236\21\5\26\0\6\5\1\0\1\5\12\0"+
    "\2\5\1\237\6\5\1\240\16\5\26\0\6\5\1\0"+
    "\1\5\12\0\5\5\1\241\22\5\26\0\6\5\1\0"+
    "\1\5\12\0\2\5\1\242\25\5\26\0\6\5\1\0"+
    "\1\5\12\0\1\5\1\243\26\5\26\0\6\5\1\0"+
    "\1\5\12\0\5\5\1\244\22\5\26\0\6\5\1\0"+
    "\1\5\12\0\13\5\1\245\14\5\26\0\6\5\1\0"+
    "\1\5\12\0\6\5\1\246\21\5\26\0\6\5\1\0"+
    "\1\5\12\0\2\5\1\247\25\5\26\0\6\5\1\0"+
    "\1\5\12\0\4\5\1\250\23\5\26\0\6\5\1\0"+
    "\1\5\12\0\1\251\27\5\26\0\6\5\1\0\1\5"+
    "\12\0\1\252\27\5\26\0\6\5\1\0\1\5\12\0"+
    "\22\5\1\253\5\5\26\0\6\5\1\0\1\5\12\0"+
    "\3\5\1\254\24\5\26\0\6\5\1\0\1\5\12\0"+
    "\17\5\1\255\10\5\26\0\6\5\1\0\1\5\12\0"+
    "\15\5\1\256\12\5\26\0\6\5\1\0\1\5\12\0"+
    "\1\257\27\5\27\0\1\222\1\0\1\222\74\0\6\5"+
    "\1\0\1\5\12\0\22\5\1\260\5\5\26\0\6\5"+
    "\1\0\1\5\12\0\13\5\1\261\14\5\26\0\6\5"+
    "\1\0\1\5\12\0\15\5\1\262\12\5\26\0\6\5"+
    "\1\0\1\5\12\0\7\5\1\263\20\5\26\0\6\5"+
    "\1\0\1\5\12\0\5\5\1\264\22\5\26\0\6\5"+
    "\1\0\1\5\12\0\11\5\1\265\16\5\26\0\6\5"+
    "\1\0\1\5\12\0\5\5\1\266\22\5\26\0\6\5"+
    "\1\0\1\5\12\0\14\5\1\267\13\5\26\0\6\5"+
    "\1\0\1\5\12\0\2\5\1\270\25\5\26\0\6\5"+
    "\1\0\1\5\12\0\14\5\1\271\13\5\26\0\6\5"+
    "\1\0\1\5\12\0\10\5\1\272\17\5\26\0\6\5"+
    "\1\0\1\5\12\0\2\5\1\273\25\5\26\0\6\5"+
    "\1\0\1\5\12\0\6\5\1\274\21\5\26\0\6\5"+
    "\1\0\1\5\12\0\3\5\1\275\24\5\26\0\6\5"+
    "\1\0\1\5\12\0\10\5\1\276\17\5\26\0\6\5"+
    "\1\0\1\5\12\0\17\5\1\277\10\5\26\0\6\5"+
    "\1\0\1\5\12\0\1\5\1\300\26\5\26\0\6\5"+
    "\1\0\1\5\12\0\2\5\1\301\25\5\26\0\6\5"+
    "\1\0\1\5\12\0\6\5\1\302\21\5\26\0\6\5"+
    "\1\0\1\5\12\0\2\5\1\303\25\5\26\0\6\5"+
    "\1\0\1\5\12\0\13\5\1\304\14\5\26\0\6\5"+
    "\1\0\1\5\12\0\6\5\1\305\21\5\26\0\6\5"+
    "\1\0\1\5\12\0\13\5\1\306\14\5\26\0\6\5"+
    "\1\0\1\5\12\0\2\5\1\307\25\5\26\0\6\5"+
    "\1\0\1\5\12\0\13\5\1\310\14\5\26\0\6\5"+
    "\1\0\1\5\12\0\13\5\1\311\14\5\26\0\6\5"+
    "\1\0\1\5\12\0\10\5\1\312\17\5\26\0\6\5"+
    "\1\0\1\5\12\0\2\5\1\313\25\5\26\0\6\5"+
    "\1\0\1\5\12\0\15\5\1\314\12\5\26\0\6\5"+
    "\1\0\1\5\12\0\16\5\1\315\11\5\26\0\6\5"+
    "\1\0\1\5\12\0\12\5\1\316\15\5\26\0\6\5"+
    "\1\0\1\5\12\0\6\5\1\317\21\5\26\0\6\5"+
    "\1\0\1\5\12\0\17\5\1\320\10\5\26\0\6\5"+
    "\1\0\1\5\12\0\14\5\1\321\13\5\26\0\6\5"+
    "\1\0\1\5\12\0\6\5\1\322\21\5\26\0\6\5"+
    "\1\0\1\5\12\0\16\5\1\323\11\5\26\0\6\5"+
    "\1\0\1\5\12\0\6\5\1\324\21\5\26\0\6\5"+
    "\1\0\1\5\12\0\1\5\1\325\26\5\26\0\6\5"+
    "\1\0\1\5\12\0\2\5\1\326\25\5\26\0\6\5"+
    "\1\0\1\5\12\0\17\5\1\327\10\5\26\0\6\5"+
    "\1\0\1\5\12\0\15\5\1\330\12\5\26\0\6\5"+
    "\1\0\1\5\12\0\5\5\1\331\22\5\26\0\6\5"+
    "\1\0\1\5\12\0\6\5\1\332\21\5\26\0\6\5"+
    "\1\0\1\5\12\0\6\5\1\333\21\5\25\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[9600];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\3\0\1\11\10\1\1\11\33\1\4\11\1\1\6\11"+
    "\2\1\1\11\1\1\1\11\3\1\1\0\3\11\1\1"+
    "\1\0\3\11\32\1\3\11\1\1\12\11\1\0\1\1"+
    "\1\11\1\1\1\11\1\0\35\1\2\11\1\1\1\0"+
    "\110\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[219];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true iff the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true iff the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */

	private Symbol symbol(int type) {
        return new Symbol(type, yyline, yycolumn);
    }

    private Symbol symbol(int type, Object value) {
        return new Symbol(type, yyline, yycolumn, value);
    }
	
	public String toString() {
          return ("line : " + (this.yyline + 1) + ", column : " + this.yycolumn + ", value :" + this.yytext());
   }



  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Lexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 192) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      if (zzMarkedPosL > zzStartRead) {
        switch (zzBufferL[zzMarkedPosL-1]) {
        case '\n':
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':  // fall through
          zzAtBOL = true;
          break;
        case '\r': 
          if (zzMarkedPosL < zzEndReadL)
            zzAtBOL = zzBufferL[zzMarkedPosL] != '\n';
          else if (zzAtEOF)
            zzAtBOL = false;
          else {
            boolean eof = zzRefill();
            zzMarkedPosL = zzMarkedPos;
            zzEndReadL = zzEndRead;
            zzBufferL = zzBuffer;
            if (eof) 
              zzAtBOL = false;
            else 
              zzAtBOL = zzBufferL[zzMarkedPosL] != '\n';
          }
          break;
        default:
          zzAtBOL = false;
        }
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      if (zzAtBOL)
        zzState = ZZ_LEXSTATE[zzLexicalState+1];
      else
        zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return new java_cup.runtime.Symbol(sym.EOF); }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { throw new RuntimeException("Illegal character \""+yytext()+
                                                              "\" at line "+yyline+", column "+yycolumn);
            } 
            // fall through
          case 90: break;
          case 2: 
            { return symbol(IDENTIFIER, yytext());
            } 
            // fall through
          case 91: break;
          case 3: 
            { return symbol(INT_CONST, yytext());
            } 
            // fall through
          case 92: break;
          case 4: 
            { return symbol(DOT, yytext());
            } 
            // fall through
          case 93: break;
          case 5: 
            { return symbol(MINUS, yytext());
            } 
            // fall through
          case 94: break;
          case 6: 
            { /* do nothing */
            } 
            // fall through
          case 95: break;
          case 7: 
            { return symbol(NEWLINE, yytext());
            } 
            // fall through
          case 96: break;
          case 8: 
            { return symbol(DIVIDE, yytext());
            } 
            // fall through
          case 97: break;
          case 9: 
            { return symbol(TIMES, yytext());
            } 
            // fall through
          case 98: break;
          case 10: 
            { return symbol(RT, yytext());
            } 
            // fall through
          case 99: break;
          case 11: 
            { return symbol(EQ, yytext());
            } 
            // fall through
          case 100: break;
          case 12: 
            { return symbol(LT, yytext());
            } 
            // fall through
          case 101: break;
          case 13: 
            { return symbol(PLUS, yytext());
            } 
            // fall through
          case 102: break;
          case 14: 
            { return symbol(MOD, yytext());
            } 
            // fall through
          case 103: break;
          case 15: 
            { return symbol(AND, yytext());
            } 
            // fall through
          case 104: break;
          case 16: 
            { return symbol(XOR, yytext());
            } 
            // fall through
          case 105: break;
          case 17: 
            { return symbol(OR, yytext());
            } 
            // fall through
          case 106: break;
          case 18: 
            { return symbol(NOT, yytext());
            } 
            // fall through
          case 107: break;
          case 19: 
            { return symbol(SEMI, yytext());
            } 
            // fall through
          case 108: break;
          case 20: 
            { return symbol(L_BRACE, yytext());
            } 
            // fall through
          case 109: break;
          case 21: 
            { return symbol(R_BRACE, yytext());
            } 
            // fall through
          case 110: break;
          case 22: 
            { return symbol(COMMA, yytext());
            } 
            // fall through
          case 111: break;
          case 23: 
            { return symbol(COLON, yytext());
            } 
            // fall through
          case 112: break;
          case 24: 
            { return symbol(LPAREN, yytext());
            } 
            // fall through
          case 113: break;
          case 25: 
            { return symbol(LBRACK, yytext());
            } 
            // fall through
          case 114: break;
          case 26: 
            { return symbol(RBRACK, yytext());
            } 
            // fall through
          case 115: break;
          case 27: 
            { return symbol('~', yytext());
            } 
            // fall through
          case 116: break;
          case 28: 
            { return symbol(QUESTION, yytext());
            } 
            // fall through
          case 117: break;
          case 29: 
            { yybegin(STRING);
            } 
            // fall through
          case 118: break;
          case 30: 
            { return symbol(LIBRARY, yytext());
            } 
            // fall through
          case 119: break;
          case 31: 
            { 
            } 
            // fall through
          case 120: break;
          case 32: 
            { yybegin(YYINITIAL); return symbol(STRING_CONST, yytext());
            } 
            // fall through
          case 121: break;
          case 33: 
            { return symbol(DOUBLE_CONST, yytext());
            } 
            // fall through
          case 122: break;
          case 34: 
            { return symbol(DEC_OP, yytext());
            } 
            // fall through
          case 123: break;
          case 35: 
            { return symbol(PTR_OP, yytext());
            } 
            // fall through
          case 124: break;
          case 36: 
            { return symbol(SUB_ASSIGN, yytext());
            } 
            // fall through
          case 125: break;
          case 37: 
            { return symbol(COMMENT, yytext());
            } 
            // fall through
          case 126: break;
          case 38: 
            { return symbol(DIV_ASSIGN, yytext());
            } 
            // fall through
          case 127: break;
          case 39: 
            { return symbol(MUL_ASSIGN, yytext());
            } 
            // fall through
          case 128: break;
          case 40: 
            { throw new RuntimeException("Illegal new line \""+yytext()+"\" in string.");
            } 
            // fall through
          case 129: break;
          case 41: 
            { return symbol(IF, yytext());
            } 
            // fall through
          case 130: break;
          case 42: 
            { return symbol(DO, yytext());
            } 
            // fall through
          case 131: break;
          case 43: 
            { return symbol(RIGHT_OP, yytext());
            } 
            // fall through
          case 132: break;
          case 44: 
            { return symbol(GE_OP, yytext());
            } 
            // fall through
          case 133: break;
          case 45: 
            { return symbol(EQ_OP, yytext());
            } 
            // fall through
          case 134: break;
          case 46: 
            { return symbol(LE_OP, yytext());
            } 
            // fall through
          case 135: break;
          case 47: 
            { return symbol(LEFT_OP, yytext());
            } 
            // fall through
          case 136: break;
          case 48: 
            { return symbol(ADD_ASSIGN, yytext());
            } 
            // fall through
          case 137: break;
          case 49: 
            { return symbol(INC_OP, yytext());
            } 
            // fall through
          case 138: break;
          case 50: 
            { return symbol(MOD_ASSIGN, yytext());
            } 
            // fall through
          case 139: break;
          case 51: 
            { return symbol(AND_ASSIGN, yytext());
            } 
            // fall through
          case 140: break;
          case 52: 
            { return symbol(AND_OP, yytext());
            } 
            // fall through
          case 141: break;
          case 53: 
            { return symbol(XOR_ASSIGN, yytext());
            } 
            // fall through
          case 142: break;
          case 54: 
            { return symbol(OR_ASSIGN, yytext());
            } 
            // fall through
          case 143: break;
          case 55: 
            { return symbol(OR_OP, yytext());
            } 
            // fall through
          case 144: break;
          case 56: 
            { return symbol(NE_OP, yytext());
            } 
            // fall through
          case 145: break;
          case 57: 
            { return symbol(ELLIPSIS, yytext());
            } 
            // fall through
          case 146: break;
          case 58: 
            { return symbol(INT, yytext());
            } 
            // fall through
          case 147: break;
          case 59: 
            { return symbol(FOR, yytext());
            } 
            // fall through
          case 148: break;
          case 60: 
            { return symbol(RIGHT_ASSIGN, yytext());
            } 
            // fall through
          case 149: break;
          case 61: 
            { return symbol(LEFT_ASSIGN, yytext());
            } 
            // fall through
          case 150: break;
          case 62: 
            { return symbol(AUTO, yytext());
            } 
            // fall through
          case 151: break;
          case 63: 
            { return symbol(ENUM, yytext());
            } 
            // fall through
          case 152: break;
          case 64: 
            { return symbol(ELSE, yytext());
            } 
            // fall through
          case 153: break;
          case 65: 
            { return symbol(CASE, yytext());
            } 
            // fall through
          case 154: break;
          case 66: 
            { return symbol(CHAR, yytext());
            } 
            // fall through
          case 155: break;
          case 67: 
            { return symbol(LONG, yytext());
            } 
            // fall through
          case 156: break;
          case 68: 
            { return symbol(GOTO, yytext());
            } 
            // fall through
          case 157: break;
          case 69: 
            { return symbol(VOID, yytext());
            } 
            // fall through
          case 158: break;
          case 70: 
            { return symbol(UNION, yytext());
            } 
            // fall through
          case 159: break;
          case 71: 
            { return symbol(BREAK, yytext());
            } 
            // fall through
          case 160: break;
          case 72: 
            { return symbol(CONST, yytext());
            } 
            // fall through
          case 161: break;
          case 73: 
            { return symbol(SHORT, yytext());
            } 
            // fall through
          case 162: break;
          case 74: 
            { return symbol(FLOAT, yytext());
            } 
            // fall through
          case 163: break;
          case 75: 
            { return symbol(WHILE, yytext());
            } 
            // fall through
          case 164: break;
          case 76: 
            { return symbol(RETURN, yytext());
            } 
            // fall through
          case 165: break;
          case 77: 
            { return symbol(EXTERN, yytext());
            } 
            // fall through
          case 166: break;
          case 78: 
            { return symbol(STATIC, yytext());
            } 
            // fall through
          case 167: break;
          case 79: 
            { return symbol(STRUCT, yytext());
            } 
            // fall through
          case 168: break;
          case 80: 
            { return symbol(SIGNED, yytext());
            } 
            // fall through
          case 169: break;
          case 81: 
            { return symbol(SIZEOF, yytext());
            } 
            // fall through
          case 170: break;
          case 82: 
            { return symbol(SWITCH, yytext());
            } 
            // fall through
          case 171: break;
          case 83: 
            { return symbol(DOUBLE, yytext());
            } 
            // fall through
          case 172: break;
          case 84: 
            { return symbol(TYPEDEF, yytext());
            } 
            // fall through
          case 173: break;
          case 85: 
            { return symbol(DEFAULT, yytext());
            } 
            // fall through
          case 174: break;
          case 86: 
            { return symbol(UNSIGNED, yytext());
            } 
            // fall through
          case 175: break;
          case 87: 
            { return symbol(REGISTER, yytext());
            } 
            // fall through
          case 176: break;
          case 88: 
            { return symbol(CONTINUE, yytext());
            } 
            // fall through
          case 177: break;
          case 89: 
            { return symbol(VOLATILE, yytext());
            } 
            // fall through
          case 178: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
